export const STRIPE_ENABLED_PAYMENT_METHODS = [
  'bancontact',
  'blik',
  'card',
  'eps',
  'giropay',
  'klarna',
  'link',
] as const;

export const PAYMENT_METHOD_TYPES = [
  'acss_debit',
  'affirm',
  'afterpay_clearpay',
  'alipay',
  'au_becs_debit',
  'bacs_debit',
  'bancontact',
  'blik',
  'boleto',
  'card',
  'cashapp',
  'customer_balance',
  'eps',
  'fpx',
  'giropay',
  'grabpay',
  'ideal',
  'klarna',
  'konbini',
  'link',
  'oxxo',
  'p24',
  'paynow',
  'paypal',
  'promptpay',
  'sepa_debit',
  'sofort',
  'us_bank_account',
  'wechat_pay',
  'zip',
] as const;

export type PaymentMethodType = (typeof PAYMENT_METHOD_TYPES)[number];
